    files = glob.glob("*.h")
    for file in files:
        print(file, end= " ")
        print(file_len(file))
        totalH += file_len(file)
    print("tot .h", end = " ")
    print(totalH)
    print()